### PR TITLE
fix new branch crash

### PR DESCRIPTION
**Pull request by vasili-zolotov**
verified that strider process no longer crashes

### CODE REVIEW

**Comment by vasili-zolotov** [comment]
@d3ming

**Comment by d3ming** [comment]
Nice!

**Comment by d3ming** [comment]
Feel free to merge when it's ready.  Btw, here's the roadmap for strider: https://github.com/Strider-CD/strider/blob/master/ROADMAP.md  You can see they made some other bug fixes around git webhooks like https://github.com/Strider-CD/strider/issues/286

**Comment by vasili-zolotov** [comment]
I see... that one is apparently related to express framework version upgrade they did.

The github part became a plug-in module in 1.4, but it looks like the bug may still be there, the code looks similar to what it was before the change.
https://github.com/Strider-CD/strider-github/blob/master/lib/index.js#L734

**Pull request merged**
