### PR TITLE
CD-116 Make strider GC script keep a higher limit

### PR DESCRIPTION
**Pull request by d3ming**
@vasili-zolotov Strider dir currently takes 222GB, I think we could free up another 50GB from that and keep a more aggressive cleaning policy on stopped AWS machines.  Thoughts?

### CODE REVIEW

**Comment by vasili-zolotov** [comment]
This shouldn't break anything, but it will reduce cache efficiency, I wonder if this is a good thing. Especially if the root cause is elsewhere, and this just buys time between failures.

I looked through the logs in `/var/log/strider-gc.log` and I see a sporadic failure when the script tries to call `vagrant destroy`:

```
9448 [default] Terminating the instance...
   9449 /home/strider/.vagrant.d/gems/gems/vagrant-aws-0.4.1/lib/vagrant-aws/action/terminate_instance.rb:26:in `call': undefined method `destroy' for nil:NilClass (NoMethodError)
   9450         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
   9451         from /home/strider/.vagrant.d/gems/gems/vagrant-aws-0.4.1/lib/vagrant-aws/action/connect_aws.rb:41:in `call'
   9452         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
   9453         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
   9454         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
   9455         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
   9456         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
   9457         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
   9458         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
   9459         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
   9460         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
   9461         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
   9462         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:51:in `call'
   9463         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
   9464         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
   9465         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
   9466         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
   9467         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
   9468         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in `action'
   9469         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/commands/destroy/command.rb:28:in `block in execute'
   9470         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/plugin/v2/command.rb:193:in `block in with_target_vms'
   9471         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/plugin/v2/command.rb:191:in `each'
   9472         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/plugin/v2/command.rb:191:in `with_target_vms'
   9473         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/commands/destroy/command.rb:27:in `execute'
   9474         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/cli.rb:38:in `execute'
   9475         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/environment.rb:484:in `cli'
   9476         from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/bin/vagrant:127:in `<top (required)>'
   9477         from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
   9478         from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

Other times, it works fine:

```
  10643 [default] Terminating the instance...
  10644 [default] Running cleanup tasks for 'puppet' provisioner...
  10645 [default] Running cleanup tasks for 'shell' provisioner...
  10646 [default] Running cleanup tasks for 'shell' provisioner...
  10647 [default] Running cleanup tasks for 'shell' provisioner...
  10648 [default] Running cleanup tasks for 'shell' provisioner...
  10649 [default] Running cleanup tasks for 'shell' provisioner...
  10650 [default] Running cleanup tasks for 'shell' provisioner...
  10651 [default] Running cleanup tasks for 'shell' provisioner...
  10652 [default] Running cleanup tasks for 'puppet' provisioner...
```

**Comment by d3ming** [comment]
@vasili-zolotov the error about destroy is because the machine is already destroyed.  I do something like 'vagrant destroy || true' in some scripts

**Comment by vasili-zolotov** [comment]
Interesting theory. I think I've seen what you describe as well. Do you think this is related to manually cleaning up the dir? We have 89 occurrences of this exception in the log.

Currently there are 131 cached dirs. That means at least that many VMs, but in actuality it's more than that, because some repos will launch multiple VMs.

This is definitely fine, as long as we don't see a thrashing effect. I wish we had a way to evaluate the impact of some of changes like this. Perhaps by tracking application metrics in stackdriver.

**Comment by d3ming** [comment]
We could make the sleep much longer than 5min to reduce thrashing too.  Because realistically we probably won't want to run this script more than say once an hour or even more

**Comment by vasili-zolotov** [comment]
You are right, running every 5 minutes is probably not necessary. By thrashing I meant github repo thrashing and VM thrashing, since they won't sit the cache as long there may be more of creating things from scratch. We don't really have data on that unfortunately.

**Comment by d3ming** [comment]
Ah yeah I get what you mean.  I made the script to run at most once every
3H so that it wouldn't immediately destroy a machine that was just created
(at least not more than once).  We should monitor it closely once we deploy
though

**Pull request merged**
